Fix failing symbol test
mapbox/vtshaver pull request #58
Opened 2022-07-18 17:09 UTC by sofita

2022-07-18 17:11 UTC, sofita commented
## Running tests on master branch to show that they fail

First test:
![image](https://user-images.githubusercontent.com/31298051/179565572-6cbed0ef-f851-412c-980b-a04634fab1db.png)

Second test:
![image](https://user-images.githubusercontent.com/31298051/179565679-5ece0337-8a43-4574-bfb5-e68ea2855d16.png)

Third test (number-format gets hit first, because it is the first one in the style):
![image](https://user-images.githubusercontent.com/31298051/179565797-1efc4a7e-85bf-4a47-a34f-d945185b4c32.png)

2022-07-18 22:56 UTC, sofita commented
## Testing on staging

Style that filters on symbolrank being 7, and downcase name including `san`
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/31298051/179625788-79a89a7c-c44f-4ba6-ade1-040980002c26.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/31298051/179625840-680822be-4535-4af4-9e83-abecc9217eb7.png">

Request succeeds
<img width="765" alt="image" src="https://user-images.githubusercontent.com/31298051/179627911-c3a81864-ee48-4443-8109-fa44d6b2fae1.png">


## Reverting staging to not use latest vtshaver
Cannot reproduce, requests are coming back as 200 😕

2022-07-19 01:15 UTC, johnk1 requested changes
Just 2 things: we should stick to .nvmrc = 16 and I have a suggest re: changelog.

2022-07-19 01:15 UTC, johnk1 commented on .nvmrc
> -16
I didn't mean to add this to the branch. Can you revert just to 16?

2022-07-19 01:15 UTC, johnk1 commented on CHANGELOG.md
> +- Add missing symbol implementations for `downcase`, `upcase`, and `number-formatter` expressions [#58](https://github.com/mapbox/vtshaver/pull/58)
It might be worth mentioning that `number-formatter` is very basic and doesn't use any of the config options passed in.

2022-07-19 15:22 UTC, johnk1 approved these changes
🎉 thanks!

2022-07-19 17:09 UTC, sofita commented
> @sofita @johnk1 Instead of adding all the nunicode headers, can we just add mason dependency for nunicode-1.8.0? I believe mason-versions.ini file is there just for that. I don't remember the nitty-gritties there but I think you can just add `nunicode=1.8` in mason-versions.ini and mention the downloaded headers directly in the system_includes just like mbgl headers.
> 
> Didn't think this through but I reckon that would be a better approach especially when the mason package is prebuilt. What do you think?

I actually tried this exact thing! `nunicode=1.8` in mason-versions but it didn't seem to work for me

2022-07-19 17:13 UTC, axrj commented
> > @sofita @johnk1 Instead of adding all the nunicode headers, can we just add mason dependency for nunicode-1.8.0? I believe mason-versions.ini file is there just for that. I don't remember the nitty-gritties there but I think you can just add `nunicode=1.8` in mason-versions.ini and mention the downloaded headers directly in the system_includes just like mbgl headers.
> > Didn't think this through but I reckon that would be a better approach especially when the mason package is prebuilt. What do you think?
> 
> @axrj I actually tried this exact thing! `nunicode=1.8` in mason-versions but it didn't seem to work for me


Ah right. Haven't checked on the history of this PR. did you try adding the include dir in the [system_includes](https://github.com/mapbox/vtshaver/blob/071c89aa4b2994f60ee7b70a5bbe7a4a39db8640/binding.gyp#L17) ? 
what error did you see? is it that the runtime symbols could not be found or build didn't go through?

2022-07-19 18:10 UTC, sofita commented
> Ah right. Haven't checked on the history of this PR. did you try adding the include dir in the [system_includes](https://github.com/mapbox/vtshaver/blob/071c89aa4b2994f60ee7b70a5bbe7a4a39db8640/binding.gyp#L17) ? what error did you see? is it that the runtime symbols could not be found or build didn't go through?
> 
> I won't hold this PR regardless as this needs to be fixed soon in production. I'll try to see later if it can be added as a mason dependency instead.

I did not add to system_includes . This line (include dir) is already there `"-isystem <(module_root_dir)/mason_packages/.link/include",` was there another line to add? I don't know what it would be for nunicode

2022-07-19 19:43 UTC, sofita commented
> > Ah right. Haven't checked on the history of this PR. did you try adding the include dir in the [system_includes](https://github.com/mapbox/vtshaver/blob/071c89aa4b2994f60ee7b70a5bbe7a4a39db8640/binding.gyp#L17) ? what error did you see? is it that the runtime symbols could not be found or build didn't go through?
> > I won't hold this PR regardless as this needs to be fixed soon in production. I'll try to see later if it can be added as a mason dependency instead.
> 
> I did not add to system_includes . This line (include dir) is already there `"-isystem <(module_root_dir)/mason_packages/.link/include",` was there another line to add? I don't know what it would be for nunicode

Will make another ticket for this, so that we can get shaving back on master

2022-07-19 20:08 UTC, merged